# Generated by Django 6.0.5 on 2026-05-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livre',
            old_name='nombre_page',
            new_name='nombre_pages',
        ),
    ]
